### PR TITLE
runtime: upgrade to use node v16

### PR DESCRIPTION
**Pull request by chenrui333**
- upgrade this action to use node v16

### CODE REVIEW

**Comment by chenrui333** [comment]
Found there is no CI for this repo, filing [a separate PR](https://github.com/coverallsapp/github-action/pull/118) on it
cc @nickmerwin

**Comment by rburgst** [comment]
is anyone at coveralls home? this is ancient and now we do get deprecation warnings in GH actions

**Comment by brunomenezes** [comment]
Hello guys, who else has permission to merge PRs on this repository besides @nickmerwin?

cc: @chenrui333, @rburgst

**Comment by philihp** [comment]
perhaps @anjin would?

**Comment by anjin** [comment]
We'll take a look, thanks for the PR!

**Comment by striezel** [comment]
@anjin
cc @nickmerwin

> We'll take a look, thanks for the PR!

Can you give us a status update on this on? How are things progressing?

**Comment by mrexox** [comment]
Hey! For the latest `v1` and `master` the github action now uses `node16`. So, I think I can close this PR.

**Pull request closed without merging**
