### PR TITLE
Address github actions deprecation warnings.

### PR DESCRIPTION
**Pull request by pmienk**

### CODE REVIEW

**Comment by pmienk** [comment]
Resolves #132 and #135

**Comment by RobinTail** [comment]
I wonder why `node_modules` is committed into the repo.
I believe it shouldn't be like that.

**Comment by pmienk** [comment]
@RobinTail - Required for github actions as documented.

**Comment by RobinTail** [comment]
> @RobinTail - Required for github actions as documented.
> 
> 
> 
> See [Creating a Javascript Action](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github).

I see the opposite recommendation 

Checking in your node_modules directory can cause problems. As an alternative, you can use a tool called @vercel/ncc to compile your code and modules into one file used for distribution.

@pmienk

**Comment by RobinTail** [comment]
I made some actions myself, and followed those recommendations on using ncc. There're also rollup and tsup suitable. Kindly suggesting you to consider committing the compiled js instead of node_modules.

**Comment by pmienk** [comment]
Sounds like a worthwhile modification, and if you have experience with it I would happily take a working pull request.

It was not within the scope of my concern, namely fixing the problems referenced by this pull.  As such I followed the path laid out by the originating repository.

**Comment by robinbowes** [comment]
It seems like using something like [@vercel/ncc](https://github.com/vercel/ncc) is preferred, but that is not in the scope of this PR, so should be fixed separately, IMO.

**Comment by RobinTail** [comment]
omg, it's already 2023 but these warning are still unfixed.

**Comment by mrexox** [comment]
I tried to fix all the warnings in `@v1.2.1` release which is also available as `@v1`. I think this PR can be closed. Please, feel free to open a new one or ping me here if you notice something unfixed.

**Pull request closed without merging**
