### PR TITLE
Support for raw coverage file

### PR DESCRIPTION
**Pull request by MikeEdgar**
Add support for user-provided raw JSON coverage file (such as the file generated by the `coveralls-maven-plugin`).

This PR uses some code authored by @ly-cultureiq in PR #25 .

- Update README with instructions for raw file and Java example

### CODE REVIEW

**Comment by MikeEdgar** [comment]
This should help with several of the issues related to "How can I use this action with X file format?" provided that users have another upstream library to create the Coveralls formatted JSON file.

CC: @nickmerwin

**Comment by MikeEdgar** [comment]
Is there any chance of this being accepted? If there is anything not in alignment with the project goals, etc. please comment and I can make adjustments if that is the case. Thanks

**Comment by portlek** [comment]
I really need that.

**Comment by casperdcl** [comment]
looks like https://github.com/AndreMiras/coveralls-python-action is a viable replacement for coverallsapp/github-action and https://github.com/AndreMiras/coveralls-python-action/pull/5 will even allow parallel builds.

**Pull request closed without merging**
